// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKfV8k8kUPRnT_O6I_4hY9x0zuTTKmTwo',
    appId: '1:989122365460:web:da90f2d6d4b1532759bf01',
    messagingSenderId: '989122365460',
    projectId: 'fluttertestapp-a124f',
    authDomain: 'fluttertestapp-a124f.firebaseapp.com',
    storageBucket: 'fluttertestapp-a124f.appspot.com',
    measurementId: 'G-MQ64PPSSEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnIQGo789CASv3M_S-h7JMr2DBbUSL6IM',
    appId: '1:989122365460:android:3804829133875de659bf01',
    messagingSenderId: '989122365460',
    projectId: 'fluttertestapp-a124f',
    storageBucket: 'fluttertestapp-a124f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-jVF-KzHk8iLXHNmF2VE-ASa3IXYkOII',
    appId: '1:989122365460:ios:ce27a28fb1da566159bf01',
    messagingSenderId: '989122365460',
    projectId: 'fluttertestapp-a124f',
    storageBucket: 'fluttertestapp-a124f.appspot.com',
    iosBundleId: 'de.vadime.fluttertestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-jVF-KzHk8iLXHNmF2VE-ASa3IXYkOII',
    appId: '1:989122365460:ios:1d832898b72a9b4359bf01',
    messagingSenderId: '989122365460',
    projectId: 'fluttertestapp-a124f',
    storageBucket: 'fluttertestapp-a124f.appspot.com',
    iosBundleId: 'de.vadime.fluttertestapp.RunnerTests',
  );
}
